export const translations = {
  fr: {
    // Header is handled by the context hook
    // Hero
    heroTitle: "Optimisez Vos",
    heroSubtitle: "Études Universitaires",
    heroDescription: "L'assistant IA pour les étudiants. Transformez vos cours, PDF et documents de recherche en cartes mentales interactives.",
    secure: "100% Sécurisé",
    instant: "Réponses Instantanées",
    university: "Idéal pour l'Université",
    // File Upload
    dropzoneHint: "Glissez-déposez un fichier ici",
    or: "ou",
    chooseFile: "Choisir un fichier",
    fileTypes: "PDF, PPTX, JPG, PNG",
    fileAdded: "Fichier ajouté !",
    // Features
    whyNodqra: "Pourquoi Nodqra ?",
    whyNodqraDesc: "Une approche révolutionnaire qui combine l'intelligence artificielle avancée pour analyser en profondeur vos documents académiques.",
    feature1Title: "IA Conversationnelle Avancée",
    feature1Desc: "Multilingue • Contextuel",
    feature2Title: "Analyse de Documents Académiques",
    feature2Desc: "Cours, Thèses, Articles",
    feature3Title: "Réponses Ultra-Rapides",
    feature3Desc: "Informations Accessible",
    feature4Title: "Base de données IA",
    feature4Desc: "Intelligente • Évolutive",
    feature5Title: "Moteur IA",
    feature5Desc: "Avancé • Apprentissage Adaptatif",
    // Footer
    privacy: "Confidentialité",
    terms: "Conditions",
    contact: "Contact",
    // Processing
    processingTitle: "Analyse en cours...",
    processingDesc: "Nodqra transforme votre document:",
    // Results
    resultsTitle: "Votre Présentation Personnalisée",
    resultsSubtitle: "Générée par l'IA de Nodqra",
    slide: "Slide",
    summaryTitle: "Résumé Détaillé",
    resetButton: "Analyser un autre document",
    // Error
    errorTitle: "Erreur de traitement",
  },
  en: {
    // Hero
    heroTitle: "Optimize Your",
    heroSubtitle: "University Studies",
    heroDescription: "The AI assistant for students. Transform your lectures, PDFs, and research papers into interactive mind maps.",
    secure: "100% Secure",
    instant: "Instant Answers",
    university: "Ideal for University",
    // File Upload
    dropzoneHint: "Drag and drop a file here",
    or: "or",
    chooseFile: "Choose a file",
    fileTypes: "PDF, PPTX, JPG, PNG",
    fileAdded: "File Added!",
    // Features
    whyNodqra: "Why Nodqra?",
    whyNodqraDesc: "A revolutionary approach that combines advanced artificial intelligence to deeply analyze your academic documents.",
    feature1Title: "Advanced Conversational AI",
    feature1Desc: "Multilingual • Contextual",
    feature2Title: "Academic Document Analysis",
    feature2Desc: "Courses, Theses, Articles",
    feature3Title: "Ultra-Fast Responses",
    feature3Desc: "Accessible Information",
    feature4Title: "AI Database",
    feature4Desc: "Intelligent • Scalable",
    feature5Title: "AI Engine",
    feature5Desc: "Advanced • Adaptive Learning",
    // Footer
    privacy: "Privacy",
    terms: "Conditions",
    contact: "Contact",
    // Processing
    processingTitle: "Analysis in progress...",
    processingDesc: "Nodqra is transforming your document:",
    // Results
    resultsTitle: "Your Personalized Presentation",
    resultsSubtitle: "Generated by Nodqra's AI",
    slide: "Slide",
    summaryTitle: "Detailed Summary",
    resetButton: "Analyze another document",
    // Error
    errorTitle: "Processing Error",
  },
  ar: {
    // Hero
    heroTitle: "حسّن دراساتك",
    heroSubtitle: "الجامعية",
    heroDescription: "المساعد الذكي للطلاب. حوّل محاضراتك وملفات PDF وأوراقك البحثية إلى خرائط ذهنية تفاعلية.",
    secure: "آمن 100%",
    instant: "إجابات فورية",
    university: "مثالي للجامعة",
    // File Upload
    dropzoneHint: "اسحب وأفلت ملفًا هنا",
    or: "أو",
    chooseFile: "اختر ملفًا",
    fileTypes: "PDF, PPTX, JPG, PNG",
    fileAdded: "تمت إضافة الملف!",
    // Features
    whyNodqra: "لماذا Nodqra؟",
    whyNodqraDesc: "نهج ثوري يجمع بين الذكاء الاصطناعي المتقدم لتحليل مستنداتك الأكاديمية بعمق.",
    feature1Title: "ذكاء اصطناعي تحادثي متقدم",
    feature1Desc: "متعدد اللغات • سياقي",
    feature2Title: "تحليل المستندات الأكاديمية",
    feature2Desc: "دورات، أطروحات، مقالات",
    feature3Title: "استجابات فائقة السرعة",
    feature3Desc: "معلومات يسهل الوصول إليها",
    feature4Title: "قاعدة بيانات الذكاء الاصطناعي",
    feature4Desc: "ذكية • قابلة للتطوير",
    feature5Title: "محرك الذكاء الاصطناعي",
    feature5Desc: "متقدم • تعلم تكيفي",
    // Footer
    privacy: "الخصوصية",
    terms: "الشروط",
    contact: "اتصل بنا",
    // Processing
    processingTitle: "جاري التحليل...",
    processingDesc: "يقوم Nodqra بتحويل مستندك:",
    // Results
    resultsTitle: "عرضك التقديمي المخصص",
    resultsSubtitle: "تم إنشاؤه بواسطة ذكاء Nodqra الاصطناعي",
    slide: "شريحة",
    summaryTitle: "ملخص تفصيلي",
    resetButton: "تحليل مستند آخر",
    // Error
    errorTitle: "خطأ في المعالجة",
  }
};

export type TranslationKeys = keyof typeof translations.en;